// <auto-generated />
namespace SmartLink.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRangeIdToDestination : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRangeIdToDestination));
        
        string IMigrationMetadata.Id
        {
            get { return "201703070719190_AddRangeIdToDestination"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
